### ISSUE TITLE
[Tweet] Video support

### ISSUE THREAD

**Issue by marco97pa** [marco97pa/Blackpink-Data#12]
Video upload is still an issue since it is still unsupported by Tweepy.

It is expected to be added in the next major release of Tweepy (4.0)

The actual code implementation of the script seems future-proof and could work out of the box by updating the library.

For more info see:
https://github.com/tweepy/tweepy/pull/1486

**Comment by dhhruv** [comment]
Maybe we can upload video without Tweepy. There are other methods..

**Comment by marco97pa** [comment]
> Maybe we can upload video without Tweepy. There are other methods..

Can you suggest me the best method to upload a video to Twitter with Python?

**Comment by dhhruv** [comment]
You can check this [link](https://github.com/twitterdev/large-video-upload-python) for more clarity on uploading large media (video / GIF / image) files asynchronously with the Twitter API, via the "chunked upload" method.
